### ISSUE TITLE
Handle “Connect wallet” fail

### ISSUE THREAD

**Issue by Yanda1** [Yanda1/swap-interface#1]
### Task
Add popup/alert functionality on “Connect wallet” fail to find a wallet that will notify the user to install or activate browser wallet extension. 

Notification message example:
"In order to connect wallet, you should have it installed as a browser extension. You can install it from [here](https://metamask.io/). Or try to check if your wallet extension is turned on and ready for incoming connections"

**Comment by aliburzhi** [comment]
#readyToreview
Handle “Connect wallet” fail #1
